name: Build Executables

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            filename: dtic-linux
          - os: macos-latest
            filename: dtic-macos
          - os: windows-latest
            filename: dtic-windows.exe

    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build executable
        run: |
          source $VENV
          poetry run pyinstaller --onefile dtic.py --name ${{ matrix.filename }}

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.filename }}
          path: dist/${{ matrix.filename }}
      
  release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Cross-platform DTIC aggregator executables
          files: |
            dist/dtic-linux
            dist/dtic-macos
            dist/dtic-windows.exe
        


          
